blueprint:
  name: Zones Changed Notification
  description: Send a notification when a person or device tracker changed (entered or left) zones.
  domain: automation
  source_url: https://github.com/dennislwy/homeassistant-blueprints/blob/main/automation/notify_changed_zones.yaml
  author: Dennis Lee
  input:
    person_entity:
      name: Person
      selector:
        entity:
          filter: 
            - domain: person
            - domain: device_tracker
    wait_duration:
      name: Duration to wait before sending notification
      description: The duration the person or device tracker must be in the new zone before sending a notification.
      default: 
        seconds: 30
      selector:
        duration: {}
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app

variables:
  # This is the state of the person when it's in this zone.
  person_entity: !input person_entity
  person_name: "{{ states[person_entity].friendly_name }}"

trigger:
  platform: state
  entity_id: !input person_entity
  for: !input wait_duration

conditions:
  condition: template
  value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"

action:
  - alias: "Notify that a person has enter or left the zone"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    message: |
      {% if is_state(person_entity, 'not_home') %}
        {{ person_name }} has left {{ trigger.from_state.state }}
      {% else %}
        {{ person_name }} is at 📍{{ trigger.to_state.state }}
      {% endif %}
