blueprint:
  name: Sensor/Switch Fault Notification
  description: >
    Performs scheduled checks on a sensor or switch and sends a notification
    if it has been in fault state for a specified duration of time.
  domain: automation
  source_url: https://github.com/dennislwy/homeassistant-blueprints/blob/main/automation/notify_sensor_switch_fault.yaml
  author: Dennis Lee

  input:
    monitor_entity:
      name: Entity to monitor
      description: The sensor or switch entity to monitor for faults.
      selector:
        entity:
          filter:
            - domain: sensor
            - domain: switch

    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          filter:
            integration: mobile_app

    trigger_time:
      name: Time to check
      description: The time of day to run the fault check.
      default: "10:00:00"
      selector:
        time: {}

    check_weekdays:
      name: Days to check
      description: Days of the week when the check should be performed.
      default:
        - mon
        - tue
        - wed
        - thu
        - fri
        - sat
        - sun
      selector:
        select:
          multiple: true
          mode: dropdown
          options:
            - label: Monday 
              value: mon
            - label: Tuesday
              value: tue
            - label: Wednesday
              value: wed
            - label: Thursday
              value: thu
            - label: Friday
              value: fri
            - label: Saturday
              value: sat
            - label: Sunday
              value: sun
              
    fault_state:
      name: Fault state
      description: State of the entity that is classify as fault
      default: unavailable

    fault_duration:
      name: Duration of fault state
      description: How long the entity in fault state before triggering notification.
      default: 
        hours: 1
      selector:
        duration: {}

    custom_message:
        name: Custom notification message
        description: >
          Optional. If provided, this message will be sent instead of the default.
        default: ""

variables:
  custom_message: !input custom_message
  monitor_entity: !input monitor_entity
  notification_message: >
      {% if custom_message | trim != '' %}
        {{ custom_message }}
      {% else %}
        🚨 {{ state_attr(monitor_entity, 'friendly_name') or monitor_entity }} is offline or unavailable
      {% endif %}
  
trigger:
  - platform: time
    at: !input trigger_time

condition:
  - condition: state
    entity_id: !input monitor_entity
    state: !input fault_state
    for: !input fault_duration

  - condition: time
    weekday: !input check_weekdays

action:
  - domain: mobile_app
    type: notify
    device_id: !input notify_device
    message: "{{ notification_message }}"
mode: single
