blueprint:
  name: Zone Changed Notification
  description: Send a notification to a device when a person changed (entered or left) zone.
  domain: automation
  source_url: https://github.com/dennislwy/homeassistant-blueprints/automation/notify_changed_zone.yaml
  author: Dennis Lee
  input:
    person_entity:
      name: Person
      selector:
        entity:
          domain: person
    notify_device:
      name: Device to notify
      description: Device needs to run the official Home Assistant app to receive notifications.
      selector:
        device:
          integration: mobile_app

trigger:
  platform: state
  entity_id: !input person_entity

variables:
  # This is the state of the person when it's in this zone.
  zone_state: "{{ states[zone_entity].name }}"
  person_entity: !input person_entity
  person_name: "{{ states[person_entity].name }}"

condition:
  condition: template
  value_template: "{{ trigger.from_state.state != trigger.to_state.state }}"

action:
  - alias: "Notify that a person has enter or left a zone"
    domain: mobile_app
    type: notify
    device_id: !input notify_device
    message: |
        {% if is_state(zone_state, 'not_home') %}
          {{ person_name }} left {{ trigger.from_state.state }}
        {% else %}
          {{ person_name }} is at {{ trigger.to_state.state }}
        {% endif %}